import type { Metadata } from "next"
import { Lato, Playfair_Display } from "next/font/google"
import "./globals.css"
import { cn } from "@/utils/class-names"

const lato = Lato({
  subsets: ["latin"],
  weight: ["100", "300", "400", "700", "900"],
  style: ["normal", "italic"],
  variable: "--font-lato",
})

const playfairDisplay = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-playfair-display",
  style: ["normal", "italic"],
  weight: ["400", "500", "600", "700", "800", "900"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

type Props = Readonly<{
  children: React.ReactNode
}>

export default function RootLayout({ children }: Props) {
  return (
    <html lang="en">
      <body className={cn(lato.variable, playfairDisplay.variable)}>
        {children}
      </body>
    </html>
  )
}
